development:
  forest_env_secret: a05bd7d60c088cb63884813804525ed82a12ef58f3f25d79a0177ea881ea7415
  forest_auth_secret: UdyMuOUJRZaXhYEeXgg8pQ
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
